# Generated by Django 4.2.4 on 2023-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegg_pathway_visualiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keggml_model',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
